import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Providers from "./provider";
import ModalRenderer from "@/components/Modals/Modals";
import RegisterSW from "./register-sw";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans")}>
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header />
          {children}
          <ModalRenderer />
          <RegisterSW />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
